@BASE_URL = http://localhost:8080
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsInN1YiI6Im5ld2F1dGh1c2VyIiwiaWF0IjoxNzcwMjU1Mjc1LCJleHAiOjE3NzAzNDE2NzV9.Ul4SwWIcyBpiYFG0JFQeTHsMn_2v07ffddC9JQUoU_8
@REFRESH_TOKEN = c02deafb-8086-42f4-8365-af792aaf961b

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "username": "newauthuser",
  "password": "admin123"
}

###
POST {{BASE_URL}}/auth/logout
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{BASE_URL}}/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}

###
POST {{BASE_URL}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}